CREATE TABLE assessor (
    assessor_id SERIAL PRIMARY KEY,
    assessor_name text NOT NULL,
    assessor_age int NOT NULL,
    assessor_profession text NOT NULL,
    assessor_email text NOT NULL,
    assessor_password text NOT NULL
);

CREATE TABLE toddler (
    assessor_id INT NOT NULL,
    toddler_id SERIAL PRIMARY KEY,
    toddler_name text NOT NULL,
    toddler_domicile text NOT NULL,
    toddler_gender INT NOT NULL,
    toddler_age INT NOT NULL,
    q1 int,
    q2 int,
    q3 int,
    q4 int,
    q5 int,
    q6 int,
    q7 int,
    q8 int,
    q9 int,
    q10 int,
    q11 int,
    q12 int,
    q13 int,
    q14 int,
    q15 int,
    q16 int,
    q17 int,
    q18 int,
    q19 int,
    q20 int,
    total_score int,
    result int,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (assessor_id) REFERENCES assessor(assessor_id)
);